services:
  github-rest:
    depends_on:
      db:
        condition: service_started
      logstash:
        condition: service_started
    container_name: github-rest
    image: git-app:4.9
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/oliq04
      - SPRING_DATASOURCE_DRIVER_CLASSNAME=org.postgresql.Driver
      - SPRING_DATASOURCE_USERNAME=oliq04
      - SPRING_DATASOURCE_PASSWORD=123456789
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - LOGSTASH_HOST=logstash
    ports:
      - '8444:8080'
    networks:
      - elk-network
  db:
    image: postgres:17.10-alpine
    container_name: db
    environment:
      - POSTGRES_USER=oliq04
      - POSTGRES_PASSWORD=123456789
    ports:
      - '5432:5432'
    networks:
      - elk-network

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: email@wp.pl
      PGADMIN_DEFAULT_PASSWORD: secret
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - elk-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.5.2
    container_name: elastic-search
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - elk-network

  logstash:
    container_name: log-stash
    build:
      context: ./logstash
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - elk-network

  kibana:
    image: docker.elastic.co/kibana/kibana:9.5.2
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk-network

networks:
  elk-network:
    name: elk-network
    driver: bridge

volumes:
  pgadmin-data:
  es_data:


