spring.application.name=githubrest
spring.jpa.hibernate.ddl-auto=validate
spring.cloud.openfeign.client.config.github.url=https://api.github.com
spring.cloud.openfeign.circuitbreaker.enabled=true
feign.circuitbreaker.enabled=true
logging.level.com.example.githubrest.client.GithubClient = DEBUG
logging.level.org.springframework.web=DEBUG